select ?x ?y
where {
    ?x <http://localhost:2020/vocab/resource/holder_copy_holder_name> ?tmp1.
    ?tmp1 <http://localhost:2020/vocab/resource/holder_copy_holder_name> ?y.
    ?y <http://localhost:2020/vocab/resource/holder_copy_holder_name> ?tmp2.
    ?tmp2 <http://localhost:2020/vocab/resource/holder_copy_holder_name> ?x.
}